Algoritmo "semnome"
Var
area, largura, comprimento, metroqua: real


Inicio



escreval("Qual o tamanho da Base?")
leia(largura)

escreval("Qual o tamnaho da Altura?")
leia(comprimento)

escreval("qual o preço por metro quadrado?")
leia(metroqua)

Aarea<- largura*comprimento

metroqua<-metroqua*area

escreval("A área do terreno é de:" ,area, " metros quadrados")
escreval("Seu preço por metro quadrado é R$" ,metroqua)

Fimalgoritmo